### PR TITLE
Add constraint on python

### PR DESCRIPTION
**Pull request by xylar**
Also:
* bump the build number
* add @xylar as a maintainer
* update the build script
* add `pip check`
* add `LICENSE`
* update license and description

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@BrentDorsey, this package is giving me trouble in `pip check` downstream:
https://github.com/conda-forge/apache-airflow-providers-google-feedstock/pull/56
I'm hoping to take over as a maintainer.

**Comment by xylar** [comment]
@conda-forge/core, would you be willing to merge this to I can become a maintainer?  I don't think I'm likely to hear from the current maintainer, who hasn't been active on conda-forge in awhile.

**Comment by h-vetinari** [comment]
Thank you for your offer to take over maintenance. Please try to give feedstock maintainers at least a week of time to respond.

Brent's GH profile shows activity this month, so he may yet see this.

**Comment by xylar** [comment]
@h-vetinari, okay, I can wait.

**Comment by xylar** [comment]
@h-vetinari and @conda-forge/core, I have given the maintainer the requested one week to respond and haven't heard anything.  Would someone be willing to merge this?

**Comment by xylar** [comment]
@synapticarbors, thanks very much!

**Pull request merged**
